# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ec994316d978dd50417dbdebb71fefc3f0da3da537d52d6b6888c5406ac501c35f6f39ffb70aff47244293f343f37580e508560719d1e7b5a29a0a8afa045bf

test:
  secret_key_base: 6956270441a14352a826ffed454e3b638041735e5e92723256e7515f8195696a1e0bbe569c20c399fca4702043d34dbcabfaebf8fd82fd6e06a1761f91e0b531

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
